INSERT INTO botc.address (id, namel, namek) VALUES (1, 'Toshkent Shahar', 'Тошкент Шаҳар');
INSERT INTO botc.address (id, namel, namek) VALUES (2, 'Buxoro viloyati', 'Бухоро вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (3, 'Samarqand viloyati', 'Самарқанд вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (4, 'Andijon viloyati', 'Андижон вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (5, 'Farg''ona viloyati', 'Фарғона вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (6, 'Jizzax viloyati', 'Жиззах вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (7, 'Xorazm viloyati', 'Хоразм вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (8, 'Namangan viloyati', 'Наманган вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (9, 'Navoiy viloyati', 'Навоий вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (10, 'Qashqadaryo viloyati', 'Қашқадарё вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (11, 'Sirdaryo viloyati', 'Сирдарё вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (12, 'Surxondaryo viloyati', 'Сурхондарё вилояти');
INSERT INTO botc.address (id, namel, namek) VALUES (13, 'Qoraqalpog''iston Respublikasi	', 'Қорақалпоғистон Республикаси');
INSERT INTO botc.address (id, namel, namek) VALUES (14, 'Toshkent viloyati', 'Тошкент вилояти');